kind: pipeline
type: docker
name: flask-swarm-deploy

steps:
  - name: build-and-push
    image: docker:24.0.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    commands:
      - docker build -t "registry.cn-chengdu.aliyuncs.com/luobai0110/weather:${DRONE_COMMIT_SHA}" .
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" registry.cn-chengdu.aliyuncs.com
      - docker push "registry.cn-chengdu.aliyuncs.com/luobai0110/weather:${DRONE_COMMIT_SHA}"


  - name: deploy-swarm
    image: docker:24.0.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - export IMAGE_TAG=${DRONE_COMMIT_SHA}
      - docker stack deploy -c docker-compose.yml weather-stack --with-registry-auth
