clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      skip-verify: true

steps:
  - name: build-and-push
    image: docker:24.0.2-dind
    environment:
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    commands:
      - dockerd-entrypoint.sh &
      - |
        # 等待 docker daemon 就绪
        until docker info 2>/dev/null; do
          echo "Waiting for docker daemon..."
          sleep 1
        done
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" registry.cn-chengdu.aliyuncs.com
      - docker build -t registry.cn-chengdu.aliyuncs.com/luobai0110/weather:${CI_COMMIT_SHA} .
      - docker push registry.cn-chengdu.aliyuncs.com/luobai0110/weather:${CI_COMMIT_SHA}

  - name: deploy-swarm
    image: docker:24.0.2-dind
    commands:
      - dockerd-entrypoint.sh &
      - |
        until docker info 2>/dev/null; do
          echo "Waiting for docker daemon..."
          sleep 1
        done
      - docker stack deploy -c docker-compose.yml weather-stack --with-registry-auth
