clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      skip-verify: true

steps:
  - name: build-and-push
    image: docker:24.0.2-dind
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    commands:
      - dockerd-entrypoint.sh &
      - |
        # 等待 docker daemon 就绪
        until docker info 2>/dev/null; do
          echo "Waiting for docker daemon..."
          sleep 1
        done
      - export IMAGE_TAG=$(date +"%Y%m%d-%H%M%S")
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" registry.cn-chengdu.aliyuncs.com
      - docker build -t registry.cn-chengdu.aliyuncs.com/luobai0110/weather:$IMAGE_TAG .
      - docker push registry.cn-chengdu.aliyuncs.com/luobai0110/weather:$IMAGE_TAG
      - echo $IMAGE_TAG > .image_tag

  - name: deploy-swarm
    image: docker:24.0.2-dind
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - dockerd-entrypoint.sh &
      - >-
        until docker info; do
          echo "Waiting for Docker daemon...";
          sleep 2;
        done
      - export IMAGE_TAG=$(cat .image_tag 2>/dev/null || date +"%Y%m%d-%H%M%S")
      - export IMAGE_NAME=registry.cn-chengdu.aliyuncs.com/luobai0110/weather:$IMAGE_TAG
      - >
        sed -i
        's|image: registry.cn-chengdu.aliyuncs.com/luobai0110/weather:.*|image: $IMAGE_NAME|g'
        docker-compose.yml
      - docker stack deploy -c docker-compose.yml nexus --with-registry-auth
  - name: cleanup-docker-cache
    image: docker:24.0.2-dind
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker builder prune -f  # 删除构建缓存
      - docker image prune -a -f # 删除悬空镜像
      - docker system df