clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      skip-verify: true
when:
  - event: push
    branch: [ refs/heads/test/*, refs/heads/release/*, refs/heads/main, test/*, release/* ]

steps:
  - name: build-and-push
    image: docker:24.0.2-dind
    when:
      - event: push
        branch: [ refs/heads/test/*, refs/heads/release/*, refs/heads/main, test/*, release/* ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    commands:
      - dockerd-entrypoint.sh &
      - |
        # 等待 docker daemon 就绪
        until docker info 2>/dev/null; do
          echo "Waiting for docker daemon..."
          sleep 1
        done
      - export IMAGE_TAG=$(TZ=Asia/Shanghai date +"%Y%m%d%H%M%S")
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" registry.cn-chengdu.aliyuncs.com
      - docker build -t registry.cn-chengdu.aliyuncs.com/doomer/nexus-feed:$IMAGE_TAG .
      - docker push registry.cn-chengdu.aliyuncs.com/doomer/nexus-feed:$IMAGE_TAG
      - echo $IMAGE_TAG > .image_tag

  - name: deploy-swarm
    image: docker:24.0.2-dind
    when:
      - event: push
        branch: [ refs/heads/test/*, refs/heads/release/*, refs/heads/main, test/*, release/* ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - dockerd-entrypoint.sh &
      - >-
        until docker info; do
          echo "Waiting for Docker daemon...";
          sleep 2;
        done
      - export IMAGE_TAG=$(cat .image_tag 2>/dev/null || date +"%Y%m%d%H%M%S")
      - export IMAGE_NAME=registry.cn-chengdu.aliyuncs.com/doomer/nexus-feed:$IMAGE_TAG
      - >
        sed -i
        's|image: registry.cn-chengdu.aliyuncs.com/doomer/nexus-feed:.*|image: $IMAGE_NAME|g'
        docker-compose.yml
      - docker stack deploy -c docker-compose.yml nexus --with-registry-auth