clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      skip-verify: true
    when:
      - event: push
        branch: [ test/*, release/*, main ]

steps:
  - name: build-and-push
    image: ghcr.io/containerd/nerdctl:1.7.7
    when:
      - event: push
        branch: [ test/*, release/*, main ]
    environment:
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    commands:
      - export IMAGE_TAG=$(TZ=Asia/Shanghai date +"%Y%m%d%H%M%S")
      - nerdctl login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" registry.cn-chengdu.aliyuncs.com
      - nerdctl build -t registry.cn-chengdu.aliyuncs.com/doomer/nexus-feed:$IMAGE_TAG .
      - nerdctl push registry.cn-chengdu.aliyuncs.com/doomer/nexus-feed:$IMAGE_TAG
      - echo $IMAGE_TAG > .image_tag
      - nerdctl rmi registry.cn-chengdu.aliyuncs.com/doomer/nexus-feed:$IMAGE_TAG

  - name: deploy-k8s
    image: bitnami/kubectl:1.33
    when:
      - event: push
        branch: [ test/*, release/*,  main ]
    environment:
      KUBE_CONFIG:
        from_secret: KUBE_CONFIG
    commands:
      - |
        mkdir -p ~/.kube
        echo "$KUBE_CONFIG" > ~/.kube/config
        chmod 600 ~/.kube/config
      - export IMAGE_TAG=$(cat .image_tag 2>/dev/null || date +"%Y%m%d%H%M%S")
      - export IMAGE_NAME=registry.cn-chengdu.aliyuncs.com/doomer/nexus-feed:$IMAGE_TAG

      - |
        if kubectl get deployment nexus-feed -n prod 2>/dev/null; then
          kubectl set image deployment/nexus-feed nexus-feed=$IMAGE_NAME -n prod
        else
          kubectl apply -f .deploy/k8s.yaml -n prod
        fi

      - kubectl rollout status deployment/nexus-feed -n prod --timeout=300s
      - kubectl get pods -n prod | grep nexus-feed